config/routes.rb
Rubyinsense::Application.routes.draw do
  match '/auth/:provider/callback' => 'home#create'
  devise_for :users, :controllers => {:registrations => 'registrations', :sessions => 'sessions'}

  scope 'api' do
    resources :questions do
      collection do
        get 'my_questions'
        get 'vote'
      end
      post 'rating', on: :member
      resources :answers
      resources :comments, only: [:create, :destroy]
    end
  end
  root :to => 'home#index'
end

app/models/answer.rb
class Answer
  include Mongoid::Document
  include Mongoid::MagicCounterCache
  include Mongo::Voteable

  belongs_to :question
  belongs_to :user

  counter_cache :question
  
  field :statement, type: String

  validate :statement, presence: true

  voteable self, :up => +1, :down => -1
end

app/models/comment.rb
class Comment
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :description,   :type => String, :default => ''
  
  belongs_to :question
  belongs_to :user

end

app/models/question.rb
class Question
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Timestamps
  include Rubyinsense::EncodeUrl

  rateable range: (0..5), raters: User

  field :statement, type: String
  field :answer_count, type: Integer, default: 0


  belongs_to :user
  has_many :answers
  has_many :comments

  validates :statement, :presence => true

  def question_posted?(current_user)
    user == current_user
  end

end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongo::Voter
  
  devise :database_authenticatable, :registerable, :validatable
  field :email,               :type => String, :default => ''
  field :encrypted_password,  :type => String, :default => ''
  field :provider,            :type => String, :default => 'Twitter'
  field :uid,                 :type => Integer
  field :fname,               :type => String
  field :lname,               :type => String
  field :twitter_handle,      :type => String
  field :image_url,           :type => String, :default => ''
  field :twitter_url,         :type => String, :default => ''

  has_many :questions
  has_many :answers
  has_many :comments

  validates :uid, :email, presence: true
  
  after_create :set_twitter_handle
  after_create :add_image_url
  after_create :add_twitter_url

  def password_required?
    false
  end

  def set_twitter_handle
    handle = Twitter.user(self.uid)[:screen_name] 
    self.set(:twitter_handle, handle)
  end

  def add_image_url
    image  = Twitter.user(self.uid)[:profile_image_url] 
    self.set(:image_url, image)
  end

  def add_twitter_url
    self.set(:twitter_url, "http://twitter.com/#{self.twitter_handle}")
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :load_question

  def new
    @answer = @question.answers.build
  end

  def create
    @answer = @question.answers.build(params['answer'])
    @answer.user = current_user
    if @answer.save
      Twitter.update('@'+ current_user.twitter_handle + " added an answer to #rubyinsense..!! Here it is " + @question.url_shortner('http://rubyinsense.heroku.com/questions/'+@question.id)) unless Rails.env.development?
      redirect_to question_path(@question)
    else
      render action: :new
    end
  end

  def edit
    @answer = @question.answers.find(params[:id])
    render action: :new
  end


  def update
    @answer = @question.answers.find(params[:id])
    if @answer.update_attributes(params[:answer])
      redirect_to question_path(@question)
    else
      render action: :edit
    end
  end
  
  def destroy
    @question = Question.find(params[:question_id])
    answer = Answer.find(params[:id])
    not_authorized unless answer.user == current_user
    answer.destroy
    flash[:notice] = 'Answer removed Successfully'
    redirect_to question_path(@question)
  end

  private

  def load_question
    @question = Question.find(params[:question_id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def not_authorized
    flash[:notice] = I18n.t('access.restrict')
    redirect_to root_url and return
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create 
    @question = Question.find(params[:question_id])
    @comment = @question.comments.build(params[:comment])
    @comment.user = current_user
    if @comment.save
      flash[:notice] = 'Comment Added Succesfully'
      redirect_to question_path(@question)
    else
      render template: 'questions/show' 
    end
  end

  def destroy
    @question = Question.find(params[:question_id])
    comment = Comment.find(params[:id])
    not_authorized unless comment.user == current_user
    comment.destroy
    flash[:notice] = 'Comment removed Successfully'
    redirect_to question_path(@question)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    #redirect_to questions_path if current_user
  end

  def create
    omniauth = request.env["omniauth.auth"]
    user = User.where(uid: omniauth['uid']).first
    if user
      flash[:notice] = "Signed in successfully."
      sign_in_and_redirect(:user, user)
      cookies[:user_id] = user.id
    else
      session[:uid] = omniauth['uid']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(params[:question])
    @question.user = current_user
    if @question.save
      Twitter.update('@'+ current_user.twitter_handle + " added a question to #rubyinsense..!! Here it is " + @question.url_shortner('http://rubyinsense.heroku.com/questions/'+@question.id)) unless Rails.env.development?
      redirect_to questions_path
    else
      render 'new'
    end
  end

  def edit
    @question = Question.find params[:id]
  end
  
  def update
    @question = Question.find params[:id]
    if @question.update_attributes(params[:question])
      redirect_to questions_path
    else
      render 'edit'
    end
  end

  def index
    @questions = Question.highest_rated
  end

  def my_questions
    @questions = current_user.questions
  end
    
  def show
    @question = Question.find(params[:id])
    @comment = @question.comments.build
  end

  def destroy
    question = current_user.questions.find(params[:id])
    question.destroy
    redirect_to questions_path
  end

  def vote
    model = params[:id].constantize
    @model = model.find(params[:id])
    current_user.vote(@answer, params[:type].to_sym)
  end

  def rating
    @question = Question.where(id: params[:id]).first
    @question.rate_and_save(params[:score], current_user)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController <  Devise::RegistrationsController 
  def build_resource(*args)
    super
    @user.uid = session[:uid]
    @user.valid?
  end

  def after_update_path_for(resource)
    questions_path
  end

  def update
    @user = User.find(current_user.id)
    if @user.update_attributes(params[:user])
      flash[:notice] = "Updated Successfully!"
      redirect_to after_update_path_for(@user)
    else
      flash[:notice] = "Unable to update your profile"
      render "edit"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper

  def path_to_view(quest)
    params[:action] == 'index' ? question_path(quest) : edit_question_path(quest)
  end


  def code_highlight(code)
    html = CodeRay.scan(code, :ruby).div(:line_numbers => :table)
    RedCloth.new(html).to_html
  end

  def is_new?(question)
    question.created_at.try(:to_date) == Date.today
  end

end

app/views/answers/_form.html.haml
.form-inputs
  = f.input :statement, :required => true, :as => :text, :input_html => { :rows => 10, :style => "width: 600px;",  :class => "form-control"}
  = f.submit 'Add answer', class: 'btn btn-info', :style => "margin-top: 10px;"

app/views/answers/new.html.haml
%legend Add Answer
= simple_form_for [@question, @answer] do |f|
  = render :partial => 'form', :locals => { :f => f }

app/views/comments/_form.html.haml
= f.input :description, :required => true, :as => :text, :input_html => { :rows => 4, class: "form-control"}
= f.input :question_id, :as => :hidden
%br
= f.submit 'Add Comment', class: 'btn btn-info'

app/views/home/index.html.haml
#questions

app/views/layouts/application.html.haml
- content_for :signed_in_options do
  %li.pull-right
    %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
      = render :partial => "questions/image", :locals => {:user => current_user}
      = current_user.try(:twitter_handle) || 'Options' 
    %ul.dropdown-menu
      %li
        %a{:href => edit_user_registration_path} My Profile
      %li
        = link_to 'Log Out', destroy_user_session_path, method: :delete
  :javascript
    $('.dropdown-toggle').dropdown();

- content_for :signed_out_options do
  %li.pull-right
    = link_to 'Sign In with Twitter', '/auth/twitter?x_auth_access_type=read'

- content_for :pills do  
  %ul.nav.nav-pills
    %li.active
      = link_to 'Home', root_path
    %li.active
      = link_to 'My Questions', my_questions_questions_path 
    - if user_signed_in?
      = yield :signed_in_options
    - else
      = yield :signed_out_options

%html
  %head
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    .header
      .logo
        RubyInsense
    .container
      #container
        = yield(:pills)
        = flash[:notice]
        = yield

app/views/questions/_comment.html.haml
- comments = @question.comments.select{|c| !c.new_record?} 
- if comments.any?
  - comments.each do |r|
    .well
      .container-fluid
        .row
          .span6
            %pre
              = r.description
      .container-fluid
        .row
          .span6
            By 
            = render :partial => "image", :locals => {:user => r.user}
            %b
              = link_to r.user.twitter_handle, r.user.twitter_url, :target => '_blank'
            %br
            %i.icon-calendar
            %small
              = r.created_at.strftime("Commented on %b %d %Y at %H:%M")
          .pull-right
            - if r.user == current_user
              = link_to 'Remove', question_comment_path(@question, r), method: :delete, class: 'btn btn-danger'

app/views/questions/_form.html.haml
= f.input :statement, :required => true, :as => :text, :input_html => { :rows => 10 }
= f.input :rating, collection: (0..5).to_a, default: 0

app/views/questions/_image.html.haml
- if user
  - if user.image_url != ''
    = image_tag user.image_url, class: "img-rounded"
  - else
    = image_tag "anonymous.jpg", class: "img-rounded"

app/views/questions/_questions.html.haml
%table.table.table-bordered.table-striped
  %thead
    %tr
      %th Question Statement
  %tbody
    - @questions.each_with_index do |quest, index|
      %tr
        %td
          = index + 1
          = link_to truncate(quest.statement), path_to_view(quest)
          .pull-right
            = link_to 'Remove', question_path(quest), method: :delete, class: 'btn btn-danger' if quest.question_posted?(current_user) 
            = link_to 'Edit', edit_question_path(quest), class: 'btn btn-primary' if quest.question_posted?(current_user) 

app/views/questions/_vote.html.haml
= link_to vote_questions_path(id: answer.id, type: :up), remote: true do
  .glyphicon.glyphicon-arrow-up
    %i 
      = answer.up_votes_count
= link_to vote_questions_path(id: answer.id, type: :down), remote: true do
  .glyphicon.glyphicon-arrow-down
    %i 
      = answer.down_votes_count

app/views/questions/edit.html.haml
%legend Edit Question

= simple_form_for @question, url: questions_path, defaults: {input_html: { class: "form-control"}} do |f|
  = render :partial => 'form', :locals => { :f => f }
  %br
  = f.submit 'Update', class: 'btn btn-info'

app/views/questions/index.html.haml
- content_for :box do
  %br
  %br
  .row
    .span3
    .span6
      = image_tag 'box.jpg', size: '600x400'
    .span3
.row
  .pull-right
    = link_to 'Add Question', new_question_path, class: 'btn btn-info'
%br
.row
.row
  - @questions.each do |ques|
    .col-lg-4.main-box
      .panel.panel-primary.box
        .panel-heading
          = render :partial => "questions/image", :locals => {:user => ques.user}
          - if is_new?(ques)
            %span.blink.new Recently Added
        .panel-body
          .question-main-div
            = truncate(ques.statement, length: 180)
          = link_to path_to_view(ques) do
            .details
              %center
                .row
                  %br
                .row
                  .btn.btn-default= "Answers : #{ques.answer_count}"
                .row
                  %br
                .row
                  %div{id: "question-rating-#{ques._id}"}
:javascript
  var questions_score = #{@questions.collect{|q| [q._id, q.rating]}.to_json}

app/views/questions/my_questions.html.haml
%h2 My Questions

= render :partial => "questions"

.row
  .pull-left
    = link_to 'Add Question', new_question_path, class: 'btn btn-info'

app/views/questions/new.html.haml
%legend Add a question
= simple_form_for @question, url: questions_path, defaults: {input_html: { class: "form-control"}} do |f|
  = render :partial => 'form', :locals => { :f => f }
  %br
  = f.submit 'Create', class: 'btn btn-info'

app/views/questions/show.html.haml
%br
.row
  .bs-example
    %span
      = render :partial => 'image', :locals => {:user => @question.user}
      = link_to @question.user.twitter_handle, @question.user.twitter_url, :target => '_blank'
    - if user_signed_in?
      %span
        .rating-block.pull-right
  %pre.highlight.prettyprint
    %h4
      =@question.statement
  .answer_box
  .pull-right
    %h5= link_to 'Add Answer', new_question_answer_path(@question), class: 'btn btn-primary'


- answers = @question.answers

- if answers.present? 
  %legend 
    %b Answers
  - answers.each do |ans|
    .row
      .bs-example
        = render :partial => 'image', :locals => {:user => ans.user}
        = link_to ans.user.twitter_handle, ans.user.twitter_url, :target => '_blank' 
        .pull-right
          - if user_signed_in?
            - if current_user == ans.user
              = link_to ' Edit', edit_question_answer_path(@question, ans), title: 'Edit', class: 'glyphicon glyphicon-edit'
              &nbsp
              = link_to ' Remove', question_answer_path(@question, ans), method: :delete, title: 'Remove', confirm: "Are you sure?", class: 'glyphicon glyphicon-trash'
              &nbsp
            - else
              %div{id: ans.id}
                = render 'vote', answer: ans
      %pre.highlight.prettyprint
        = raw code_highlight(ans.statement)

%legend 
  %b Comments
= render 'comment'
- if user_signed_in?
  = simple_form_for [@question, @comment] do |f|
    = render 'comments/form', f: f

:javascript
  var question = #{@question.to_json}
  var current_user_question_rating = #{@question.user_mark(current_user) || 0}

app/views/questions/vote.js.haml
$("##{@answer.id}").html("#{escape_javascript( render :partial => 'vote', locals: {answer: @answer} )}")